apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: evilpetclinic
  name: evilpetclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evilpetclinic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: evilpetclinic
    spec:
      containers:
      - image: rbenavente/evilpetclinic:latest   ##  rbenavente/evilpetclinic:latest or solalraveh/evilpetclinic:latest or harbor-master-test.rbenavente.demo.twistlock.com/library/evilpetclinic:latest  
        name: evilpetclinic
        imagePullPolicy: IfNotPresent
        resources: {}
        securityContext:
          privileged: true
        ports:
        - containerPort: 80
          name: evilpetclinic
          protocol: TCP
      imagePullSecrets:
      - name: regcred
      securityContext:
        runAsUser: 0
      hostNetwork: false

status: {}
